### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by MigdaliaBrito** [gngrninja/PSElvUI#2]
Hi.

I noticed that the readme was not updated for Powershell core.

**Comment by gngrninja** [comment]
Thanks for the report! I will get on this for the next release 👍

**Comment by gngrninja** [comment]
Migdalia,

I have updated the readme to reflect the requested changes, and make things more clear. Thanks again for the report.

Fixed here:
[Updating readme](https://github.com/gngrninja/PSElvUI/commit/8b0e7b6f8425765c5c826c933f8c1821299ec953)
