### ISSUE TITLE
Not Receiving Updates For TBC

### ISSUE THREAD

**Issue by carneios-dev** [gngrninja/PSElvUI#5]
This stopped working with a WowEdition value of 'Classic' at some point. The following is a screenshot of the result of the command:
![image](https://user-images.githubusercontent.com/84555447/119536241-78664880-bd4e-11eb-9554-b4a14c81d9b1.png)

The following is a screenshot of the version on the ElvUI git as of today:
![image](https://user-images.githubusercontent.com/84555447/119536700-fc203500-bd4e-11eb-965a-0f0a33ce764f.png)

Looks like there may have been some project detail changes in the web API for their Git, as seen [here](https://git.tukui.org/api/v4/projects/).

Let me know if you need any additional information.

**Comment by gngrninja** [comment]
I added support for TBC in the latest release, and have updated the version available on the PowerShell Gallery as well.

Give it a go, and let me know. 

`Invoke-ElvUICheck -WowEdition TBC -Verbose`

**Comment by carneios-dev** [comment]
Works great, thanks.
