### ISSUE TITLE
Error When Updating to 12.25

### ISSUE THREAD

**Issue by carneios-dev** [gngrninja/PSElvUI#7]
After attempting to update to the new 12.25 update of ElvUI in the new 9.1 patch for WoW, I receive the following error:

![image](https://user-images.githubusercontent.com/84555447/123853499-25e6f180-d8e3-11eb-8838-5d9058760dca.png)

Let me know if you need anything more information regarding this.

**Comment by gngrninja** [comment]
Thanks for the report. Are you able to test with the latest code from this commit? https://github.com/gngrninja/PSElvUI/commit/fef167c6e39cc4603c3cfa596b1657f52d2cce7f

Either way, I will test it out tomorrow when I can and then update the module on the gallery, if successful.

**Comment by gngrninja** [comment]
This has been fixed in the latest version I published to the gallery. Let me know if you continue to have issues.
