### ISSUE TITLE
Checking the installed version after updating gives an error

### ISSUE THREAD

**Issue by Chudius** [gngrninja/PSElvUI#9]
Hey man! I made a github account just to say thank you for this command. Been using it since BfA (I think).
I just uninstalled version 1.2.0 and installed 1.2.1 to be able to use it on shadowlands installation as well.

After running the command, it found an update of Elvui, Installed the update. Then when verifying I get an error. ElvUI is updated (checked ingame).

Thanks again!

````
PS C:\WINDOWS\system32> Invoke-ElvUICheck

New version of ElvUI found! (you have [12.44], latest is [12.51])


Downloading file from [https://www.tukui.org/downloads/elvui-12.51.zip]... to [C:\Users\Maurice\AppData\Local\Temp\elvui-12.51.zip]


Verifying local version has been updated...

Error determining ElvUI version -> [No luck finding version in file]!
At C:\Program Files\WindowsPowerShell\Modules\PSElvUI\1.2.1\functions\private\Get-LocalElvUiVersion.ps1:68 char:13
+             throw "Error determining ElvUI version -> [$errorMessage] ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error determini...rsion in file]!:String) [], RuntimeException
    + FullyQualifiedErrorId : Error determining ElvUI version -> [No luck finding version in file]!
```
`

**Comment by gngrninja** [comment]
My apologies for the delay in response!

I appreciate the thanks, and will look into this.

**Comment by gngrninja** [comment]
Greetings! This should be resolved with the latest commit here, as well as published to the gallery. 

If you use
`Update-Module PSElvUI -Force`

it should update and allow you to run the command without errors.

Let me know if you have any trouble!
